package org.cloudbus.cloudsim.examples.autoscaling;

import org.cloudbus.cloudsim.Cloudlet;
import org.cloudbus.cloudsim.CloudletSchedulerTimeShared;
import org.cloudbus.cloudsim.EX.DatacenterBrokerEX;
import org.cloudbus.cloudsim.Vm;
import org.cloudbus.cloudsim.core.CloudSim;
import org.cloudbus.cloudsim.core.SimEntity;
import org.cloudbus.cloudsim.core.SimEvent;
import org.cloudbus.cloudsim.core.CloudSimTags;

import org.cloudbus.cloudsim.examples.autoscaling.AutoscalingConfig;
import org.cloudbus.cloudsim.examples.autoscaling.controller.AutoscalingController;
import org.cloudbus.cloudsim.examples.autoscaling.state.CloudState;
import org.cloudbus.cloudsim.examples.autoscaling.state.CloudStateCollector;

import java.util.ArrayList;
import java.util.List;

/**
 * Runtime autoscaling manager.
 *
 * Responsibilities:
 *
 * 1. Periodically collect the current cloud state.
 * 2. Send the state to the autoscaling controller.
 * 3. Apply the returned scaling action.
 *
 * Action:
 *     -1 = scale down by one VM
 *      0 = maintain
 *     +1 = scale up by one VM
 *
 * This class does NOT contain the scaling policy.
 * The policy is implemented by ThresholdAutoscaler.
 */
public class AutoscalingManager extends SimEntity {

    /**
     * Internal event used to trigger a scaling decision.
     */
    private enum AutoscalingTag implements CloudSimTags {
        AUTOSCALING_DECISION
    }
    /**
     * Broker responsible for VM creation/destruction
     * and cloudlet execution.
     */
    private final DatacenterBrokerEX broker;

    /**
     * Threshold/controller implementation.
     */
    private final AutoscalingController controller;

    /**
     * Cloud state collector.
     */
    private final CloudStateCollector stateCollector;

    /**
     * Current VM list.
     */
    private final List<Vm> vmList;

    /**
     * Cloudlets generated by the workload.
     */
    private final List<Cloudlet> cloudletList;

    /**
     * Datacenter ID used for VM creation.
     */
    private final int datacenterId;

    /**
     * Next VM ID.
     */
    private int nextVmId;

    /**
     * Number of scaling actions.
     */
    private int totalScaleOutActions;

    private int totalScaleInActions;

    /**
     * Constructor.
     */
    public AutoscalingManager(
            String name,
            DatacenterBrokerEX broker,
            AutoscalingController controller,
            CloudStateCollector stateCollector,
            List<Vm> vmList,
            List<Cloudlet> cloudletList,
            int datacenterId) throws Exception {

        super(name);

        this.broker = broker;
        this.controller = controller;
        this.stateCollector = stateCollector;
        this.vmList = vmList;
        this.cloudletList = cloudletList;
        this.datacenterId = datacenterId;

        /*
         * VM IDs already used by the initial VM list
         * are assumed to start from 0.
         */
        this.nextVmId = findNextVmId();

        this.totalScaleOutActions = 0;
        this.totalScaleInActions = 0;
    }

    /**
     * Called when the simulation starts.
     */
    @Override
    public void startEntity() {

        System.out.println(
                CloudSim.clock()
                        + ": AutoscalingManager started."
        );

        /*
         * First decision occurs after one decision interval.
         *
         * t = 10
         * t = 20
         * t = 30
         * ...
         */
        schedule(
                getId(),
                AutoscalingConfig.DECISION_INTERVAL,
                AutoscalingTag.AUTOSCALING_DECISION
        );
    }

    /**
     * Process simulation events.
     */
    @Override
    public void processEvent(SimEvent event) {

        if (event == null) {
            return;
        }

        if (event.getTag() == AutoscalingTag.AUTOSCALING_DECISION) {

            performAutoscalingDecision();

            /*
             * Schedule the next decision.
             */
            if (CloudSim.clock()
                    + AutoscalingConfig.DECISION_INTERVAL
                    <= AutoscalingConfig.SIMULATION_TIME) {

                schedule(
                        getId(),
                        AutoscalingConfig.DECISION_INTERVAL,
                        AutoscalingTag.AUTOSCALING_DECISION
                );
            }
        }
    }

    /**
     * Collect the current state and make a scaling decision.
     */
    private void performAutoscalingDecision() {

        double currentTime =
                CloudSim.clock();

        /*
         * Calculate average CPU utilization
         * of the currently active VMs.
         */
        double cpuUtilization =
                calculateAverageCpuUtilization(
                        currentTime
                );

        /*
         * Current workload.
         *
         * For this first integration, we keep the
         * existing workload representation.
         *
         * Later this should become an arrival-rate
         * or recent-window request metric.
         */
        double workload =
                cloudletList.size();

        /*
         * Collect current cloud state.
         */
        CloudState state =
                stateCollector.collectState(

                        currentTime,

                        workload,

                        cpuUtilization,

                        vmList.size(),

                        cloudletList
                );

        /*
         * Ask the controller what to do.
         */
        int action =
                controller.decide(state);

        /*
         * Print the observation and decision.
         */
        System.out.println(
                String.format(
                        "AUTOSCALER | "
                                + "Time=%.1f | "
                                + "CPU=%.2f%% | "
                                + "VMs=%d | "
                                + "Action=%+d",
                        currentTime,
                        cpuUtilization,
                        vmList.size(),
                        action
                )
        );

        /*
         * Apply the action.
         */
        applyScalingAction(action);
    }

    /**
     * Apply the controller's action.
     */
    private void applyScalingAction(int action) {

        switch (action) {

            case +1:

                scaleOut();

                break;

            case -1:

                scaleIn();

                break;

            case 0:

                /*
                 * No scaling action.
                 */
                break;

            default:

                System.out.println(
                        "AutoscalingManager: "
                                + "Unknown action "
                                + action
                );
        }
    }

    /**
     * Scale out by one VM.
     */
    private void scaleOut() {

        /*
         * Safety check.
         */
        if (vmList.size()
                >= AutoscalingConfig.MAX_INSTANCES) {

            System.out.println(
                    "AUTOSCALER | "
                            + "Scale-out blocked: "
                            + "MAX_INSTANCES reached."
            );

            return;
        }

        /*
         * Create the new VM.
         */
        Vm vm =
                createVm(nextVmId);

        nextVmId++;

        /*
         * Add it to our active VM list.
         */
        vmList.add(vm);

        /*
         * Ask the CloudSimEx broker to create the VM
         * during the running simulation.
         *
         * Delay = 0 means creation is requested
         * at the current simulation time.
         */
        List<Vm> newVmList =
                new ArrayList<>();

        newVmList.add(vm);

        broker.createVmsAfter(
                newVmList,
                0
        );

        totalScaleOutActions++;

        System.out.println(
                "AUTOSCALER | "
                        + "SCALE OUT | "
                        + "Created VM #"
                        + vm.getId()
                        + " | "
                        + "Active VMs="
                        + vmList.size()
        );
    }

    /**
     * Scale in by one VM.
     */
    private void scaleIn() {

        // Never go below the configured minimum number of VMs.
        if (vmList.size() <= AutoscalingConfig.MIN_INSTANCES) {
            return;
        }

        /*
         * Find an idle VM that is safe to destroy.
         *
         * We iterate from the end of the list so that, when possible,
         * newer VMs are removed first.
         */
        Vm vmToRemove = null;

        double currentTime = CloudSim.clock();

        for (int i = vmList.size() - 1; i >= 0; i--) {

            Vm vm = vmList.get(i);

            /*
             * Current CPU utilization of this VM.
             */
            double cpuUtilization =
                    vm.getTotalUtilizationOfCpu(currentTime);

            /*
             * Treat very small CPU utilization as idle.
             */
            if (cpuUtilization <= 0.001) {
                vmToRemove = vm;
                break;
            }
        }

        /*
         * No idle VM was found.
         *
         * Do NOT destroy a busy VM because DatacenterBrokerEX will
         * fail cloudlets currently associated with that VM.
         */
        if (vmToRemove == null) {

            System.out.println(
                    "AUTOSCALER | SCALE IN SKIPPED | "
                            + "No idle VM available"
            );

            return;
        }

        /*
         * Ask the broker to destroy the selected VM.
         */
        List<Vm> destroyList = new ArrayList<>();
        destroyList.add(vmToRemove);

        broker.destroyVMsAfter(destroyList, 0);

        /*
         * Remove it from the autoscaler's active VM list.
         */
        vmList.remove(vmToRemove);

        totalScaleInActions++;

        System.out.println(
                "AUTOSCALER | SCALE IN | Destroyed VM #"
                        + vmToRemove.getId()
                        + " | Active VMs="
                        + vmList.size()
        );
    }
    /**
     * Create a VM using the project's VM configuration.
     */
    private Vm createVm(int vmId) {

        return new Vm(

                vmId,

                broker.getId(),

                AutoscalingConfig.VM_MIPS,

                AutoscalingConfig.VM_PES,

                AutoscalingConfig.VM_RAM,

                AutoscalingConfig.VM_BW,

                AutoscalingConfig.VM_SIZE,

                "Xen",

                new CloudletSchedulerTimeShared()
        );
    }

    /**
     * Calculate average CPU utilization across
     * currently active VMs.
     */
    private double calculateAverageCpuUtilization(
            double currentTime) {

        if (vmList.isEmpty()) {
            return 0.0;
        }

        double totalUtilization =
                0.0;

        for (Vm vm : vmList) {

            if (vm != null) {

                totalUtilization +=
                        vm.getTotalUtilizationOfCpu(
                                currentTime
                        );
            }
        }

        return (
                totalUtilization
                        / vmList.size()
        ) * 100.0;
    }

    /**
     * Find the next available VM ID.
     */
    private int findNextVmId() {

        int maxId = -1;

        for (Vm vm : vmList) {

            if (vm != null
                    && vm.getId() > maxId) {

                maxId = vm.getId();
            }
        }

        return maxId + 1;
    }

    /**
     * Number of scale-out actions.
     */
    public int getTotalScaleOutActions() {

        return totalScaleOutActions;
    }

    /**
     * Number of scale-in actions.
     */
    public int getTotalScaleInActions() {

        return totalScaleInActions;
    }

    /**
     * Shut down the manager.
     */
    @Override
    public void shutdownEntity() {

        System.out.println(
                CloudSim.clock()
                        + ": AutoscalingManager shutting down."
        );
    }
}